# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from . import WordRequestType

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal
        EnumTypeWordRequestType = Literal[None, 0, 1, 2]
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore
        EnumTypeWordRequestType = None


class WordRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 46

    def __init__(
        self,
        type: EnumTypeWordRequestType = None,
    ) -> None:
        self.type = type

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('type', p.EnumType(WordRequestType), 0),
        }
