# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamECCPoint(p.MessageType):
    MESSAGE_WIRE_TYPE = 911

    def __init__(
        self,
        x: bytes = None,
        y: bool = None,
    ) -> None:
        self.x = x
        self.y = y

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('x', p.BytesType, 0),
            2: ('y', p.BoolType, 0),
        }
